version: '3'

volumes:
  emby:

services:
  emby:
    image: emby/embyserver
    container_name: emby
    restart: always
    networks:
      - web
    volumes:
      - emby:/config
      - /media/wdhdd/Media/Movies:/mnt/movies
      - /media/wdhdd/Media/Shows:/mnt/shows
    devices:
      - /dev/dri/renderD128
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.routers.emby.rule=Host(`emby.snackk-media.com`)"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"

    environment:
      - UID: 1000
      - GID: 1000

networks:
  web:
    external: true
