version: '3'

volumes:
  emby:

services:
  emby:
    image: emby/embyserver
    container_name: emby
    restart: always  
    networks:
      - web
    volumes:
      - emby:/config
      - /media/wdhdd/Media/Movies:/mnt/movies
      - /media/wdhdd/Media/Shows:/mnt/shows
    devices:
      - /dev/dri/renderD128
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:emby.snackk-media.com"      
      - "traefik.port=8096"
      - "traefik.backend=emby"  
    environment:
      - UID: 1000 
      - GID: 1000

networks:
  web:
    external: true