version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/traefik.toml
      - ${PWD}/acme.json:/acme.json
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=9001"
      - "traefik.backend=traefik"
      - "traefik.frontend.auth.basic=snackk:$$apr1$$4rzTfR6u$$1KWcbCpqRVMoszfZv2.XV/"

networks:
  web:
    external: true

