debug = false
logLevel = "ERROR"

defaultEntryPoints = ["https", "http"]

[entryPoints]
    [entryPoints.http]
    	address = ":80"

        [entryPoints.http.redirect]
	        entryPoint = "https"
	        permanent = true

	[entryPoints.https]
		address = ":443"
		compress = true
		[entryPoints.https.tls]

	[entryPoints.dashboard]
		address = ":8080"
		compress = true

		[entryPoints.traefik.auth.basic]
		  users = ["snackk:$$apr1$$4rzTfR6u$$1KWcbCpqRVMoszfZv2.XV/"]    

[retry]

[api]
	entryPoint = "dashboard"
	dashboard = true

[docker]
	endpoint = "unix:///var/run/docker.sock"
	domain = "docker.localhost"
	watch = true
	exposedByDefault = true

[acme]
	email = "snackk026@gmail.com"
	storage = "acme.json"
	entryPoint = "https"
	onHostRule = true

	[acme.httpChallenge]
		entryPoint = "http"

