[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [http.middlewares]
      [http.middlewares.test-compress.compress]  
  [entryPoints.http]
    address = ":80"
    [http.middlewares]
      [http.middlewares.test-redirectscheme.redirectScheme]
        scheme = "https"
  [entryPoints.https]
    address = ":443"
    [http.middlewares]
      [http.middlewares.test-compress.compress]  
  [entryPoints.traefik]
    [http.middlewares]
      [http.middlewares.test-auth.basicAuth]
        users = [
          "snackk:$apr1$$4rzTfR6u$$1KWcbCpqRVMoszfZv2.XV/",
        ]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmModeRefreshSeconds = "15s"

[api]
  insecure = true
  dashboard = true

[log]
  level = "ERROR"

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "snackk026@gmail.com"
      storage = "acme.json"
      [certificatesResolvers.default.acme.httpChallenge]
        entryPoint = "http"