version: "3.7"

volumes:
  db:
  nextcloud:

services:
  db:
    image: mariadb
    container_name: mysql
    restart: always
    networks:
      - internal
    volumes:
      - db:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    environment:
      - MYSQL_ROOT_PASSWORD: secret
      - MYSQL_PASSWORD:
      - MYSQL_DATABASE: nextcloud
      - MYSQL_USER: nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stoped
    networks:
      - web
      - internal
    volumes:
      - ./data:/var/www/html
    links:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.snackk-media.com`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.snackk-media.com`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=http"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  internal:
    driver: bridge
  web:
    external: true
