version: '3'

volumes:
  db:
  nextcloud:

services:
  db:
    image: mariadb
    container_name: mysql    
    restart: always
    networks:
      - internal    
    volumes:
      - db:/var/lib/mysql
    labels:
      - "traefik.enable=false"        
    environment:
      - MYSQL_ROOT_PASSWORD: secret
      - MYSQL_PASSWORD:
      - MYSQL_DATABASE: nextcloud
      - MYSQL_USER: nextcloud    

  nextcloud:
    image: nextcloud
    container_name: nextcloud    
    restart: always
    networks:
      - web
      - internal    
    volumes:
      - nextcloud:/var/www/html
    links:
      - db
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:nextcloud.snackk-media.com"      
      - "traefik.port=80"
      - "traefik.backend=nextcloud"

networks:
  internal:
    driver: bridge
  web:
    external: true