version: '3'

volumes:
  db:
  nextcloud:

services:
  db:
    image: mariadb
    container_name: mysql    
    restart: always
    networks:
      - internal    
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels:
      - "traefik.enable=false"      

  app:
    image: nextcloud
    container_name: nextcloud    
    restart: always
    networks:
      - web
      - internal    
    volumes:
      - nextcloud:/var/www/html
    links:
      - db
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:nextcloud.localhost"      
      - "traefik.port=80"
      - "traefik.backend=nextcloud"

networks:
  internal:
  web:
    external: true