version: "3.7"

volumes:
  portainer:

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer:/data"
    labels:
      # Portainer exposure
      - "traefik.docker.network=web"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.snackk-media.com`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"

networks:
  web:
    external: true
