version: '3'

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config:/config
      - /media/movies:/downloads
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:transmission.snackk-media.com"      
      - "traefik.port=9091"
      - "traefik.backend=transmission"
    environment:
      - PUID: ${userid} 
      - PGID: ${groupid}


networks:
  web:
    external: true      